import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import getHomeService, { ContactData, Map } from '@services/homeService'
import { SpecialityDto, specialityDto } from '@services/dto/specialityDto'
import { GetFormat, getFormat } from 'src/utils/getFormat'
import HeroHome from '@components/Home/HeroHome/HeroHome'
import Contact from '@components/Home/Contact/Contact'

const Home: NextPage<HomeProps> = ({ specialities, backgroundColor, background, title, contactData, map }) => {
  return (
    <>
      <Head>
        <title>Osteosalix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroHome title={title} bgColor={backgroundColor} bgImage={background} bubbles={specialities} />
      <Contact contactData={contactData} map={map} />
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const HomeInfo = await getHomeService();
  const { locale, specialities: banner, title, contactSection } = HomeInfo.data.attributes;
  const { specialities, backgroundColor, backgroundImage } = banner;

  return {
    props: {
      specialities: specialities.map(speciality => specialityDto(speciality)) || [],
      backgroundColor,
      background: getFormat(backgroundImage),
      title,
      contactData: contactSection,
      map: contactSection.map,
      headerCompact: true
    }
  }
}

export default Home

type HomeProps = {
  locale: string;
  title: string;
  specialities: SpecialityDto[];
  backgroundColor: string;
  background: GetFormat | string | null;
  contactData: ContactData;
  map: Map;
}
