import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import BasicLayout, { HeaderInfo } from '@components/shared/Layouts/BasicLayout/BasicLayout'
import getBasicLayoutService from '@services/getBaseLayoutService'

const Home: NextPage<HomeProps> = ({ headerInfo }) => {
  console.log('headerInfo: ', headerInfo)
  return (
    <>
      <Head>
        <title>Osteosalix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout headerInfo={headerInfo}>
        <h1>Hola...</h1>
      </BasicLayout>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const headerInfo = await getBasicLayoutService();
  const { Logo } = headerInfo.data.attributes;

  console.log(Logo)

  return {
    props: {
      headerInfo: {
        logo: {
          id: Logo.id,
          name: Logo.image.data.attributes.name,
          url: `${process.env.SERVER_URL}${Logo.image.data.attributes.url}`,
          width: Logo.image.data.attributes.width
        }
      }
    }
  }
}

export default Home

type HomeProps = {
  locale: string
  headerInfo: HeaderInfo;
}
