import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import BasicLayout, { HeaderInfo } from '@components/shared/Layouts/BasicLayout/BasicLayout'
import getBasicLayoutService from '@services/getBaseLayoutService'
import getHomeService from '@services/homeService'
import { SpecialityDto, specialityDto } from '@services/dto/specialityDto'
import { GetFormat, getFormat } from 'src/utils/getFormat'
import HeroHome from '@components/Home/HeroHome/HeroHome'

const Home: NextPage<HomeProps> = ({ headerInfo, specialities, backgroundColor, background, title }) => {
  return (
    <>
      <Head>
        <title>Osteosalix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout headerInfo={headerInfo}>
        <HeroHome title={title} bgColor={backgroundColor} bgImage={background} bubbles={specialities} />
      </BasicLayout>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const headerInfo = await getBasicLayoutService();
  const { Logo } = headerInfo.data.attributes;

  const HomeInfo = await getHomeService();
  const { locale, specialities: banner, title } = HomeInfo.data.attributes;
  const { specialities, backgroundColor, backgroundImage } = banner;

  return {
    props: {
      headerInfo: {
        logo: {
          id: Logo.id,
          name: Logo.image.data.attributes.name,
          url: `${process.env.SERVER_URL}${Logo.image.data.attributes.url}`,
          width: Logo.image.data.attributes.width
        }
      },
      specialities: specialities.map(speciality => specialityDto(speciality)) || [],
      backgroundColor,
      background: getFormat(backgroundImage),
      title
    }
  }
}

export default Home

type HomeProps = {
  locale: string;
  title: string;
  headerInfo: HeaderInfo;
  specialities: SpecialityDto[];
  backgroundColor: string;
  background: GetFormat | string | null;
}
